blog/urls.py
from django.urls import path
from .views import (
	ArticleList,
	ArticleDetail,
	ArticlePreview,
	CategoryList,
	AuthorList,
	SearchList
)

app_name = "blog"
urlpatterns = [
	path('', ArticleList.as_view(), name="home"),
	path('page/<int:page>', ArticleList.as_view(), name="home"),
	path('article/<slug:slug>', ArticleDetail.as_view(), name="detail"),
	path('preview/<int:pk>', ArticlePreview.as_view(), name="preview"),
	path('category/<slug:slug>', CategoryList.as_view(), name="category"),
	path('category/<slug:slug>/page/<int:page>', CategoryList.as_view(), name="category"),
	path('author/<slug:username>', AuthorList.as_view(), name="author"),
	path('author/<slug:username>/page/<int:page>', AuthorList.as_view(), name="author"),
	path('search/', SearchList.as_view(), name="search"),
	path('search/page/<int:page>', SearchList.as_view(), name="search"),
]

comment/api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

from comment.api import views

urlpatterns = [
    path('comments/', views.CommentList.as_view(), name='comments-list'),
    path('comments/create/', views.CommentCreate.as_view(), name='comments-create'),
    path('comments/<int:pk>/', views.CommentDetail.as_view(), name='comment-detail'),
    path('comments/<int:pk>/react/<str:reaction>/', views.CommentDetailForReaction.as_view(), name='comments-react'),
    path('comments/<int:pk>/flag/', views.CommentDetailForFlag.as_view(), name='comments-flag'),
    path(
        'comments/<int:pk>/flag/state/change/',
        views.CommentDetailForFlagStateChange.as_view(),
        name='comments-flag-state-change'
    ),
]

urlpatterns = format_suffix_patterns(urlpatterns)

comment/urls.py
from django.urls import path

from comment.views import CreateComment, UpdateComment, DeleteComment, SetReaction, SetFlag, ChangeFlagState

app_name = 'comment'

urlpatterns = [
    path('create/', CreateComment.as_view(), name='create'),
    path('edit/<int:pk>/', UpdateComment.as_view(), name='edit'),
    path('delete/<int:pk>/', DeleteComment.as_view(), name='delete'),
    path('<int:pk>/react/<str:reaction>/', SetReaction.as_view(), name='react'),
    path('<int:pk>/flag/', SetFlag.as_view(), name='flag'),
    path('<int:pk>/flag/state/change/', ChangeFlagState.as_view(), name='flag-change-state')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from account.views import Login, Register, activate

urlpatterns = [
    path('', include('blog.urls')),
    path('', include('django.contrib.auth.urls')),
    path('login/', Login.as_view(), name='login'),
    path('register/', Register.as_view(), name='register'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', activate, name='activate'),
    re_path(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
    path('comment/', include('comment.urls')),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comment/forms.py
from django import forms

from comment.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', )
        widgets = {'content': forms.Textarea(attrs={'rows': 1})}

comment/api/views.py
from django.core.exceptions import ValidationError
from django.contrib.contenttypes.models import ContentType
from rest_framework import generics, permissions, status
from rest_framework.exceptions import PermissionDenied
from rest_framework.generics import get_object_or_404
from rest_framework.response import Response

from comment.api.serializers import CommentSerializer, CommentCreateSerializer
from comment.api.permissions import (
    IsOwnerOrReadOnly, ContentTypePermission, ParentIdPermission, FlagEnabledPermission, CanChangeFlaggedCommentState
)
from comment.models import Comment, Reaction, ReactionInstance, Flag, FlagInstance


class CommentCreate(generics.CreateAPIView):
    serializer_class = CommentCreateSerializer
    permission_classes = (permissions.IsAuthenticated, ContentTypePermission, ParentIdPermission)

    def get_serializer_context(self):
        context = super().get_serializer_context()
        context['user'] = self.request.user
        context['model_type'] = self.request.GET.get("type")
        context['model_id'] = self.request.GET.get("id")
        context['parent_id'] = self.request.GET.get("parent_id")
        return context


class CommentList(generics.ListAPIView):
    serializer_class = CommentSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly, ContentTypePermission)

    def get_queryset(self):
        model_type = self.request.GET.get("type")
        pk = self.request.GET.get("id")
        content_type_model = ContentType.objects.get(model=model_type.lower())
        model_class = content_type_model.model_class()
        model_obj = model_class.objects.filter(id=pk).first()
        return Comment.objects.filter_parents_by_object(model_obj)


class CommentDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly)


class CommentDetailForReaction(generics.RetrieveAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

    def get_serializer_context(self):
        context = super().get_serializer_context()
        context['reaction_update'] = True
        return context

    def post(self, request, *args, **kwargs):
        comment = get_object_or_404(Comment, id=kwargs.get('pk'))
        reaction_type = kwargs.get('reaction', None)
        reaction_obj = Reaction.objects.get_reaction_object(comment)
        try:
            ReactionInstance.objects.set_reaction(
                user=request.user,
                reaction=reaction_obj,
                reaction_type=reaction_type
            )
        except ValidationError as e:
            return Response({'error': e.messages}, status=status.HTTP_400_BAD_REQUEST)

        comment.reaction.refresh_from_db()
        serializer = self.get_serializer(comment)
        return Response(serializer.data, status=status.HTTP_200_OK)


class CommentDetailForFlag(generics.RetrieveAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly, FlagEnabledPermission)

    def get_serializer_context(self):
        context = super().get_serializer_context()
        context['flag_update'] = True
        return context

    def post(self, request, *args, **kwargs):
        comment = get_object_or_404(Comment, id=kwargs.get('pk'))
        flag = Flag.objects.get_for_comment(comment)
        reason = request.data.get('reason') or request.POST.get('reason')
        info = request.data.get('info') or request.POST.get('info')
        try:
            FlagInstance.objects.set_flag(request.user, flag, reason=reason, info=info)
        except ValidationError as e:
            return Response({'error': e.messages}, status=status.HTTP_400_BAD_REQUEST)

        serializer = self.get_serializer(comment)
        return Response(serializer.data, status=status.HTTP_200_OK)


class CommentDetailForFlagStateChange(generics.RetrieveAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer
    permission_classes = (CanChangeFlaggedCommentState, )

    def get_serializer_context(self):
        context = super().get_serializer_context()
        context['flag_update'] = True
        return context

    def post(self, request, *args, **kwargs):
        comment = get_object_or_404(Comment, id=kwargs.get('pk'))
        flag = Flag.objects.get_for_comment(comment)
        if not comment.is_flagged:
            raise PermissionDenied(detail='You do not have permission to perform this action.')
        state = request.data.get('state') or request.POST.get('state')
        try:
            state = flag.get_clean_state(state)
            if not comment.is_edited and state == flag.RESOLVED:
                return Response(
                    {'error': 'The comment must be edited before resolving the flag'},
                    status=status.HTTP_400_BAD_REQUEST
                )
            flag.toggle_state(state, request.user)
        except ValidationError as e:
            return Response({'error': e.messages}, status=status.HTTP_400_BAD_REQUEST)

        serializer = self.get_serializer(comment)
        return Response(serializer.data, status=status.HTTP_200_OK)

comment/views/comments.py
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse, HttpResponseBadRequest
from django.core.exceptions import PermissionDenied
from django.template.loader import render_to_string
from django.views.generic import FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import EmailMessage
from django.contrib.sites.shortcuts import get_current_site
from django.urls import reverse

from comment.models import Comment
from comment.forms import CommentForm
from comment.utils import get_comment_context_data, get_model_obj, is_comment_admin, is_comment_moderator


class BaseCommentView(LoginRequiredMixin, FormView):
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = context.pop('form')
        context.update(get_comment_context_data(self.request))
        return context

    def post(self, request, *args, **kwargs):
        if not request.is_ajax():
            return HttpResponseBadRequest('Only AJAX request are allowed')
        return super().post(request, *args, **kwargs)


class CreateComment(BaseCommentView):
    comment = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment'] = self.comment
        return context

    def get_template_names(self):
        if self.comment.is_parent:
            return ['comment/comments/base.html']
        else:
            return ['comment/comments/child_comment.html']

    def form_valid(self, form):
        app_name = self.request.POST.get('app_name')
        model_name = self.request.POST.get('model_name')
        model_id = self.request.POST.get('model_id')
        model_object = get_model_obj(app_name, model_name, model_id)
        parent_id = self.request.POST.get('parent_id')
        parent_comment = None
        if parent_id:
            parent_qs = Comment.objects.filter(id=parent_id)
            if parent_qs.exists():
                parent_comment = parent_qs.first()
        comment_content = form.cleaned_data['content']
        self.comment = Comment.objects.create(
            content_object=model_object,
            content=comment_content,
            user=self.request.user,
            parent=parent_comment,
        )

        # send email section
        current_site = get_current_site(self.request)
        article = self.comment.content_object
        author_email = article.author.email
        user_email = self.comment.user.email
        if author_email == user_email:
            author_email = False
            user_email = False
        parent_email = False
        if self.comment.parent:
            parent_email = self.comment.parent.user.email
            if parent_email in [author_email, user_email]:
                parent_email = False

        if author_email:
            email = EmailMessage(
                        "دیدگاه جدید",
                        "دیدگاه جدیدی برای مقاله «{}» که شما نوینده آن هستید، ارسال شده:\n{}{}".format(article, current_site, reverse('blog:detail', kwargs={'slug': article.slug})),
                        to=[author_email]
            )
            email.send()

        if user_email:
            email = EmailMessage(
                        "دیدگاه دریافت شد",
                        "دیدگاه شما دریافت شد و به زودی به آن پاسخ می دهیم.",
                        to=[user_email]
            )
            email.send()

        if parent_email:
            email = EmailMessage(
                        "پاسخ به دیدگاه شما",
                        "پاسخی به دیدگاه شما در مقاله «{}» ثبت شده است. برای مشاهده بر روی لینک زیر کلیک کنید:\n{}{}".format(article, current_site, reverse('blog:detail', kwargs={'slug': article.slug})),
                        to=[parent_email]
            )
            email.send()

        return self.render_to_response(self.get_context_data())


class UpdateComment(BaseCommentView):
    comment = None

    def dispatch(self, request, *args, **kwargs):
        self.comment = get_object_or_404(Comment, pk=self.kwargs.get('pk'))
        if request.user != self.comment.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        context = self.get_context_data()
        context['comment_form'] = CommentForm(instance=self.comment)
        context['comment'] = self.comment
        return render(request, 'comment/comments/update_comment.html', context)

    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST, instance=self.comment)
        context = self.get_context_data()
        if form.is_valid():
            form.save()
            context['comment'] = self.comment
            return render(request, 'comment/comments/comment_content.html', context)


class DeleteComment(BaseCommentView):
    comment = None

    def dispatch(self, request, *args, **kwargs):
        self.comment = get_object_or_404(Comment, pk=self.kwargs.get('pk'))
        if request.user != self.comment.user and not is_comment_admin(request.user) \
                and not (self.comment.is_flagged and is_comment_moderator(request.user)):
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        data = dict()
        context = self.get_context_data()
        context["comment"] = self.comment
        data['html_form'] = render_to_string('comment/comments/comment_modal.html', context, request=request)
        return JsonResponse(data)

    def post(self, request, *args, **kwargs):
        self.comment.delete()
        context = self.get_context_data()
        return render(request, 'comment/comments/base.html', context)

comment/views/flags.py
from django.conf import settings
from django.core.exceptions import ValidationError, PermissionDenied
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseBadRequest, JsonResponse, HttpResponseForbidden
from django.shortcuts import get_object_or_404
from django.utils.translation import gettext_lazy as _
from django.views import View

from comment.models import Comment, Flag, FlagInstance
from comment.utils import is_comment_admin, is_comment_moderator


class FlagViewMixin(LoginRequiredMixin, View):
    comment = None

    def dispatch(self, request, *args, **kwargs):
        if not getattr(settings, 'COMMENT_FLAGS_ALLOWED', 0):
            return HttpResponseForbidden(_('Flagging system must be enabled'))

        if not request.is_ajax():
            return HttpResponseBadRequest(_('Only AJAX request are allowed'))
        self.comment = get_object_or_404(Comment, pk=self.kwargs.get('pk'))
        return super().dispatch(request, *args, **kwargs)


class SetFlag(FlagViewMixin):

    def post(self, request, *args, **kwargs):
        response = {
            'status': 1
        }
        flag = Flag.objects.get_for_comment(self.comment)

        try:
            if FlagInstance.objects.set_flag(request.user, flag, **request.POST.dict()):
                response['msg'] = _('Comment flagged')
                response['flag'] = 1
            else:
                response['msg'] = _('Comment flag removed')

            response.update({
                'status': 0
            })
        except ValidationError as e:
            response.update({
                'msg': e.messages
            })

        return JsonResponse(response)


class ChangeFlagState(FlagViewMixin):

    def dispatch(self, request, *args, **kwargs):
        self.comment = get_object_or_404(Comment, pk=self.kwargs.get('pk'))
        if not self.comment.is_flagged:
            raise PermissionDenied
        if not is_comment_admin(request.user) and not is_comment_moderator(request.user):
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        state = request.POST.get('state')
        try:
            self.comment.flag.toggle_state(state, request.user)
        except ValidationError:
            return JsonResponse({'state': 0})
        response = {
            'state': self.comment.flag.state
        }
        return JsonResponse(response)

comment/templates/comment/comments/apply_icon.html
<button class="{% block apply_btn_cls %}btn btn-link{% endblock apply_btn_cls %}" type="submit" name="form_type">
{% block apply_img_icon %}
<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24"
        fill="none" stroke="{% block apply_icon_color %}#00bc8c{% endblock apply_icon_color %}" stroke-width="2" stroke-linecap="round"
        stroke-linejoin="round" class="feather feather-check">
    <polyline points="20 6 9 17 4 12"></polyline>
</svg>
{% endblock apply_img_icon %}
</button>

comment/templates/comment/comments/base.html
{% load comment_tags %}
<script>window.CSRF_TOKEN = "{{ csrf_token }}"</script>
<section id="comments" class="{% block comment_section_cls %}my-5 mx-3{% endblock comment_section_cls %}">
    <strong class="border-bottom bb"><span class="js-comment-number">{% get_comments_count model_object user %}</span> دیدگاه</strong>
    <hr class="hr"/>
    <div class="js-comment comment mb-5">
        {% include 'comment/comments/create_comment.html' with placeholder="دیدگاهی بنویسید ..." comment=None %}
    </div>
    <div class="js-main-comment mt-5">
      {% for comment in comments %}
          {% include 'comment/comments/parent_comment.html' with placeholder='پاسخی بنویسید ...' %}
      {% endfor %}
    </div>
    <div class="modal fade" id="Modal">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
        </div>
    </div>
    </div>
    {% if comments.paginator.num_pages > 1 %}
    {% block pagination %}
    {% include 'comment/comments/pagination.html' with active_btn='bg-success' text_style='text-success' li_cls='page-item rounded mx-1' %}
    {% endblock pagination %}
    {% endif %}
</section>

comment/templates/comment/comments/cancel_icon.html
<a class="js-comment-cancel {% block cancel_btn_cls %}btn btn-link{% endblock cancel_btn_cls %}" href="#">
{% block cancel_img_icon %}
<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24"
     fill="none" stroke="{% block cancel_icon_color %}#E74C3C{% endblock cancel_icon_color %}" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x">
    <line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line>
</svg>
{% endblock cancel_img_icon %}
</a>

comment/templates/comment/comments/comment_body.html
{% load comment_tags %}
<div class="row">
    {% if has_valid_profile %}
        <div class="{% block image_wrapper_cls %}col-2 col-md-1{% endblock image_wrapper_cls %}">
            <a href="{% get_profile_url comment %}">
                <img class="{% block image_cls %}w-100{% endblock image_cls %}"
                     src="{% get_img_path comment %}" alt="{{comment.user.username}}">
            </a>
        </div>
    {% endif %}
    {% include 'comment/comments/comment_content.html' with comment=comment %}
    {% if allowed_flags and comment.user != user %}
        <div class="col-1">
            {% include "comment/flags/flags.html" %}
        </div>
    {% endif %}
</div>

comment/templates/comment/comments/comment_form.html
{% load comment_tags %}
{% if comment_form.non_field_errors %}
    <div class='alert alert-danger' role='alert'>
        {% for error in comment_form.non_field_errors %}
            {{ error }}
        {% endfor %}
    </div>
{% endif %}
{% for field in comment_form.visible_fields %}
       {% render_field field placeholder=placeholder class='js-comment-input form-control form-control-sm rounded-0' %}
{% endfor %}

comment/templates/comment/comments/content.html
<p class="js-comment-content {% block c_text_cls %}mb-0{% endblock c_text_cls %}">
    {% if text_2 %}
        {{ text_1 }}
        <span class="d-none">{{ text_2 }}</span>
        <button class="js-read-more-btn btn btn-link btn-xs" style="font-size: 14px">ادامه ...</button>
    {% else %}
        {{ text_1 }}
    {% endif %}
</p>

comment/templates/comment/comments/create_comment.html
{% load comment_tags %}
{% if user.is_authenticated %}
    <form class="js-comment-form" method="post" data-url="{% url 'comment:create' %}">
        {% csrf_token %}
        <div class="row">
            <div class="{% block text_area_wrapper_cls %}col-sm-9 col-md-10 px-2 m-2 m-sm-0{% endblock text_area_wrapper_cls %}">
                {% include 'comment/comments/comment_form.html' with placeholder=placeholder %}
            </div>
            <input name="model_name" value="{% get_model_name model_object %}" hidden>
            <input name="model_id" value="{{ model_object.id }}" hidden>
            <input name="app_name" value="{% get_app_name model_object %}" hidden>
            <input name="comments_per_page" value="{{comments_per_page}}" hidden>
            <input name="oauth" value="{{oauth}}" hidden>
            {% if comment %}
            <input name="parent_id" value="{{ comment.id }}" type="hidden"/>
            {% endif %}
            <div class="{% block submit_button_wrapper_cls %}col-sm-3 col-md-2 px-2 m-3 m-sm-0{% endblock submit_button_wrapper_cls %}">
                <button disabled class="js-comment-btn {% block submit_button_cls %}btn btn-outline-success btn-block btn-sm{% endblock submit_button_cls %}"
                        type="submit" name="form_type" data-type="{% if comment %}child{% else %}parent{% endif %}">
                    {% if comment %}پاسخ{% else %}ارسال{% endif %}
                </button>
            </div>
        </div>
    </form>
{% else %}
    <div class="d-flex mb-3">
        <p class="text-danger {% if comment %}h7 my-auto {% endif %}"><em>ارسال دیدگاه:</em></p>
        <a class="mx-2 text-success {% if comment %}h7 my-auto {% endif %}" href="{{login_url}}?next={{request.path}}">ورود</a>
        {% if oauth %}
            {% block oauth %}
            <a class="mx-1 my-0 h4 github-color" href="{% url 'social:begin' 'github' %}?next={{request.path}}"><i class="fa fa-github-square"></i></a>
            <a class="mx-1 my-0 h4 facebook-color" href="{% url 'social:begin' 'facebook' %}?next={{request.path}}"><i class="fa fa-facebook-square"></i></a>
            <a class="mx-1 my-0 h4 twitter-color" href="{% url 'social:begin' 'twitter' %}?next={{request.path}}"><i class="fa fa-twitter-square"></i></a>
            <a class="mx-1 my-0 h4 google-color" href="{% url 'social:begin' 'google-oauth2' %}?next={{request.path}}"><i class="fa fa-google-plus-square"></i></a>
            {% endblock oauth %}
        {% endif %}
    </div>
{% endif %}

comment/templates/comment/comments/edit_icon.html
{% load comment_tags %}
<a title="Edit comment" class="js-comment-edit {% block edit_link_cls %}btn btn-link{% endblock edit_link_cls %}"
   href="{% url 'comment:edit' pk=comment.id %}?comments_per_page={{comments_per_page}}&model_name={% get_model_name model_object %}&model_id={{ model_object.id }}&app_name={% get_app_name model_object %}&oauth={{oauth}}">
{% block edit_img_icon %}
<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none"
     stroke="{% block edit_icon_color %}#00bc8c{% endblock edit_icon_color %}"
     stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit">
    <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path>
    <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path>
</svg>
{% endblock edit_img_icon %}
</a>

comment/templates/comment/comments/parent_comment.html
{% load comment_tags %}
<div class="js-parent-comment blockquote text-wrap">
    {% include 'comment/comments/comment_body.html' with comment=comment %}
    <div class="js-replies mr-5 my-4 d-none">
        {% get_comment_replies comment user as replies %}
        {% for comment in replies %}
            {% include 'comment/comments/child_comment.html' %}
        {% endfor %}
        {% include 'comment/comments/create_comment.html' with placeholder=placeholder %}
    </div>
    <hr/>
</div>

comment/templates/comment/comments/reject_icon.html
{% load comment_tags %}
<button title="{% if comment.has_rejected_state %}Flag rejected{% else %}Reject the flag{% endif %}" class="js-flag-reject {% block reject_btn_cls %}btn btn-link{% endblock reject_btn_cls %}" data-state="{{ comment.flag.REJECTED }}" data-url="{% url 'comment:flag-change-state' pk=comment.id %}">

{% block reject_img_icon %}
<svg class="{% if comment.has_rejected_state %}flag-rejected{% endif %}"
     xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24"
     fill="none" stroke="{% block reject_icon_color %}#E74C3C{% endblock reject_icon_color %}"
     stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">
     <path d="m19.216 15.194c0.31035 0.06374 0.55087-0.12433 0.77177-0.18337 4e-3 -0.0037 7e-3 -0.0065 9e-3 -0.0084 6e-3 -3.9981 3e-3 -8.0025 3e-3 -12.003 0 0-1 1-4 1s-5-2-8-2-4 1-4 1v12"></path>
     <line x1="4" x2="4" y1="22" y2="15"></line>
     <g transform="matrix(1.0063 0 0 1.0063 50.624 -.78936)">
      <g transform="matrix(1.1808 0 0 1.1808 55.855 .43703)">
       <path d="m-83.031 14.926 6.7248-6.7248"></path>
       <path d="m-76.306 14.926-6.7248-6.7248"></path>
      </g>
     </g>
</svg>
{% endblock reject_img_icon %}
</button>

comment/templates/comment/comments/resolve_icon.html
{% load comment_tags %}
<button title="{% if comment.has_resolved_state %}Flag resolved{% else %}Resolve the flag{% endif %}" class="js-flag-resolve {% block resolved_btn_cls %}btn btn-link{% endblock resolved_btn_cls %}" data-state="{{ comment.flag.RESOLVED }}" data-url="{% url 'comment:flag-change-state' pk=comment.id %}">

{% block resolved_img_icon %}
<svg class="{% if comment.has_resolved_state %}flag-resolved{% endif %}"
     xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24"
     fill="none" stroke="{% block resolved_icon_color %}#E74C3C{% endblock resolved_icon_color %}"
     stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">
     <path d="m11.939 20.395c-2.3228-3.8704-6.6445-2.2732-10.044-1.5539l0.10519-15.842h6c1.9144 0.42177 3.3887 1.4863 3.9187 3.1939"></path>
     <path d="m7.2106 9.7002 3.6287 5.1401 8.115-13.216" stroke-width="2.5"></path>
     <path d="m11.939 20.395c2.3228-3.8704 6.6445-2.2732 10.044-1.5539l-0.10519-15.841"></path>
</svg>
{% endblock resolved_img_icon %}
</button>

comment/templates/comment/comments/update_comment.html
{% load comment_tags %}
<div class="col-10 col-md-11">
    <form class="js-comment-edit-form" method="post" data-url="{% url 'comment:edit' pk=comment.id %}">
        {% csrf_token %}
        {% include 'comment/comments/comment_form.html' with placeholder=placeholder %}
        <footer class="blockquote-footer edit-comment mt-2">
            <small>
                <input name="model_name" value="{% get_model_name model_object %}" hidden>
                <input name="model_id" value="{{ model_object.id }}" hidden>
                <input name="app_name" value="{% get_app_name model_object %}" hidden>
                <input name="comments_per_page" value="{{comments_per_page}}" hidden>
                <input name="oauth" value="{{oauth}}" hidden>

                {% include 'comment/comments/apply_icon.html' %}
                {% include 'comment/comments/cancel_icon.html' %}
            </small>
        </footer>
    </form>
</div>